"""Add fuel_pumps and fuel_pump_deliveries tables

Revision ID: 5fa7c6ca7595
Revises: a1b2c3d4e5f6
Create Date: 2025-12-14 11:31:37.591941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '5fa7c6ca7595'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define enums - fueltype already exists, pumpstatus is new
fueltype = postgresql.ENUM('diesel', 'petrol', 'gasoline', 'electric', 'hybrid', 'lpg', 'cng', name='fueltype', create_type=False)
pumpstatus = postgresql.ENUM('active', 'inactive', 'maintenance', 'out_of_service', name='pumpstatus', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the pumpstatus enum first (fueltype already exists)
    pumpstatus.create(op.get_bind(), checkfirst=True)

    op.create_table('fuel_pumps',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', fueltype, nullable=False),
    sa.Column('status', pumpstatus, nullable=False),
    sa.Column('capacity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_level', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_level', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_odometer', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('next_maintenance_date', sa.Date(), nullable=True),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuel_pump_deliveries',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('pump_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_time', sa.Time(), nullable=True),
    sa.Column('volume', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('receipt_image', sa.String(length=500), nullable=True),
    sa.Column('pump_odometer_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pump_odometer_after', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('level_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('level_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pump_id'], ['fuel_pumps.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fuel_entries', sa.Column('pump_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('fuel_entries', sa.Column('pump_odometer', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_foreign_key('fuel_entries_pump_id_fkey', 'fuel_entries', 'fuel_pumps', ['pump_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fuel_entries_pump_id_fkey', 'fuel_entries', type_='foreignkey')
    op.drop_column('fuel_entries', 'pump_odometer')
    op.drop_column('fuel_entries', 'pump_id')
    op.drop_table('fuel_pump_deliveries')
    op.drop_table('fuel_pumps')
    # Drop the pumpstatus enum
    pumpstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
