"""Initial migration

Revision ID: 2be4e79def67
Revises:
Create Date: 2025-12-12 15:00:54.297381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2be4e79def67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create tables WITHOUT circular foreign keys first
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo', sa.String(length=500), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('distance_unit', sa.Enum('KM', 'MI', name='distanceunit'), nullable=False),
    sa.Column('volume_unit', sa.Enum('L', 'GAL', name='volumeunit'), nullable=False),
    sa.Column('fuel_efficiency_format', sa.Enum('KM_PER_L', 'L_PER_100KM', 'MPG', name='fuelefficiencyformat'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('users',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'FLEET_MANAGER', 'OPERATOR', 'VIEWER', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('cost_centers',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_period', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='budgetperiod'), nullable=True),
    sa.Column('current_spend', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('manager_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['cost_centers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    # 2. Create drivers and vehicles WITHOUT circular foreign keys
    op.create_table('drivers',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_DUTY', 'OFF_DUTY', 'ON_LEAVE', 'SUSPENDED', 'ON_BREAK', 'ON_TRIP', name='driverstatus'), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_issue_date', sa.Date(), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('license_class', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('emergency_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('cost_center_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('total_trips', sa.Integer(), nullable=False),
    sa.Column('total_distance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fuel_efficiency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('safety_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('vehicles',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('registration_plate', sa.String(length=50), nullable=False),
    sa.Column('vin', sa.String(length=17), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SEDAN', 'SUV', 'TRUCK', 'VAN', 'PICKUP', 'MOTORCYCLE', 'BUS', 'HEAVY_TRUCK', 'TRAILER', name='vehicletype'), nullable=False),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'PETROL', 'GASOLINE', 'ELECTRIC', 'HYBRID', 'LPG', 'CNG', name='fueltype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'IN_MAINTENANCE', 'INACTIVE', 'OUT_OF_SERVICE', 'IN_TRANSIT', 'IDLE', name='vehiclestatus'), nullable=False),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('current_odometer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_capacity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('assigned_driver_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('cost_center_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('registration_expiry', sa.Date(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_odometer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('average_fuel_efficiency', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('total_fuel_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_maintenance_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    # 3. Add circular foreign keys after both tables exist
    op.create_foreign_key(
        'fk_drivers_assigned_vehicle',
        'drivers', 'vehicles',
        ['assigned_vehicle_id'], ['id'],
        ondelete='SET NULL'
    )
    op.create_foreign_key(
        'fk_vehicles_assigned_driver',
        'vehicles', 'drivers',
        ['assigned_driver_id'], ['id'],
        ondelete='SET NULL'
    )

    # 4. Create remaining tables
    op.create_table('geofences',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('CIRCLE', 'POLYGON', name='geofencetype'), nullable=False),
    sa.Column('center_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('center_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('radius', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alert_on_entry', sa.Boolean(), nullable=False),
    sa.Column('alert_on_exit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('maintenance_schedules',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('interval_type', sa.Enum('MILEAGE', 'TIME', 'BOTH', name='intervaltype'), nullable=False),
    sa.Column('interval_mileage', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('last_completed_date', sa.Date(), nullable=True),
    sa.Column('last_completed_odometer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('next_due_odometer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('trips',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('driver_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('start_longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('start_heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('start_accuracy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('end_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('end_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('end_heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('end_accuracy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('max_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('average_speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('idle_time', sa.Integer(), nullable=True),
    sa.Column('fuel_consumed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('vehicle_groups',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('documents',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.Enum('VEHICLE', 'DRIVER', 'ORGANIZATION', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'EXPIRING_SOON', 'EXPIRED', 'PENDING', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('gps_alerts',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('SPEEDING', 'GEOFENCE_ENTRY', 'GEOFENCE_EXIT', 'HARSH_BRAKING', 'HARSH_ACCELERATION', 'IDLE', name='alerttype'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'WARNING', 'ERROR', 'SUCCESS', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('trip_positions',
    sa.Column('trip_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('vehicle_group_members',
    sa.Column('vehicle_group_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_group_id'], ['vehicle_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('cost_allocations',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('cost_center_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.Enum('FUEL', 'MAINTENANCE', 'INSURANCE', 'REGISTRATION', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('source_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('fuel_entries',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('driver_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fuel_type', sa.Enum('DIESEL', 'PETROL', 'GASOLINE', 'ELECTRIC', 'HYBRID', 'LPG', 'CNG', name='fueltype'), nullable=False),
    sa.Column('odometer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('previous_odometer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fuel_efficiency', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('station', sa.String(length=255), nullable=True),
    sa.Column('station_address', sa.Text(), nullable=True),
    sa.Column('receipt_number', sa.String(length=100), nullable=True),
    sa.Column('receipt_image', sa.String(length=500), nullable=True),
    sa.Column('full_tank', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cost_center_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('maintenance_tasks',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'INSPECTION', 'RECALL', 'EMERGENCY', 'OIL_CHANGE', 'TIRE_ROTATION', 'BRAKE_SERVICE', 'ENGINE_SERVICE', 'TRANSMISSION_SERVICE', name='maintenancetype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='maintenancestatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='maintenancepriority'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('due_odometer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('completed_odometer', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('actual_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parts_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('service_provider', sa.String(length=255), nullable=True),
    sa.Column('service_provider_contact', sa.String(length=255), nullable=True),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('attachments', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('work_order_number', sa.String(length=100), nullable=True),
    sa.Column('cost_center_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_centers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_tasks')
    op.drop_table('fuel_entries')
    op.drop_table('cost_allocations')
    op.drop_table('vehicle_group_members')
    op.drop_table('trip_positions')
    op.drop_table('notifications')
    op.drop_table('gps_alerts')
    op.drop_table('documents')
    op.drop_table('vehicle_groups')
    op.drop_table('trips')
    op.drop_table('maintenance_schedules')
    op.drop_table('geofences')

    # Drop circular foreign keys before dropping tables
    op.drop_constraint('fk_vehicles_assigned_driver', 'vehicles', type_='foreignkey')
    op.drop_constraint('fk_drivers_assigned_vehicle', 'drivers', type_='foreignkey')

    op.drop_table('vehicles')
    op.drop_table('drivers')
    op.drop_table('cost_centers')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
