"""add_consumables_module

Revision ID: 39ae89ae2feb
Revises: a7f76ee12c80
Create Date: 2026-04-01 15:28:51.187786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ae89ae2feb'
down_revision: Union[str, None] = 'a7f76ee12c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumables',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('erp_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.Enum('piece', 'box', 'pair', 'set', 'kg', 'gram', 'liter', 'ml', 'meter', 'roll', 'can', 'bottle', 'tube', 'sheet', name='consumableunit'), nullable=False),
    sa.Column('current_quantity', sa.Integer(), nullable=False),
    sa.Column('minimum_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('in_stock', 'low_stock', 'out_of_stock', 'ordered', 'retired', name='consumablestatus'), nullable=False),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['tool_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['tool_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['tool_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'erp_code', name='uq_consumables_org_erp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumables')
    # ### end Alembic commands ###