"""add SAT module tables

Revision ID: 8458a52615f9
Revises: f7a8b9c0d1e2
Create Date: 2026-04-14 17:01:37.441946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8458a52615f9'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sat_customers',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phc_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phc_id')
    )
    op.create_table('sat_service_types',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sat_specializations',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sat_contacts',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['sat_customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sat_employee_specializations',
    sa.Column('employee_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('specialization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialization_id'], ['sat_specializations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'specialization_id')
    )
    op.create_table('sat_machines',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('machine_type', sa.Enum('cnc', 'software', name='machinetype'), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=True),
    sa.Column('location_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['sat_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sat_assistances',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('phc_id', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('machine_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('technician_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('service_type_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='assistancepriority'), nullable=False),
    sa.Column('status', sa.Enum('requested', 'scheduled', 'en_route', 'on_site', 'completed', 'reviewed', 'cancelled', name='assistancestatus'), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('sla_response_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_resolution_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['sat_customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['machine_id'], ['sat_machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_type_id'], ['sat_service_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technician_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phc_id')
    )
    op.create_table('sat_intervention_reports',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assistance_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('technician_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('actions_taken', sa.Text(), nullable=True),
    sa.Column('parts_replaced', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('time_travel_minutes', sa.Integer(), nullable=True),
    sa.Column('time_onsite_minutes', sa.Integer(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('ai_raw_transcription', sa.Text(), nullable=True),
    sa.Column('ai_structured_draft', sa.Text(), nullable=True),
    sa.Column('customer_signature_url', sa.String(length=500), nullable=True),
    sa.Column('report_status', sa.Enum('draft', 'submitted', 'approved', name='reportstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assistance_id'], ['sat_assistances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['technician_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sat_attachments',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('intervention_report_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assistance_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.Enum('photo', 'audio', 'document', name='attachmentfiletype'), nullable=False),
    sa.Column('source', sa.Enum('whatsapp', 'web_upload', name='attachmentsource'), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assistance_id'], ['sat_assistances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervention_report_id'], ['sat_intervention_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'employees',
        sa.Column('is_sat_technician', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_sat_technician')
    op.drop_table('sat_attachments')
    op.drop_table('sat_intervention_reports')
    op.drop_table('sat_assistances')
    op.drop_table('sat_machines')
    op.drop_table('sat_employee_specializations')
    op.drop_table('sat_contacts')
    op.drop_table('sat_specializations')
    op.drop_table('sat_service_types')
    op.drop_table('sat_customers')
    bind = op.get_bind()
    for enum_name in (
        'attachmentsource',
        'attachmentfiletype',
        'reportstatus',
        'assistancestatus',
        'assistancepriority',
        'machinetype',
    ):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
