"""add tool management module

Revision ID: a7f76ee12c80
Revises: f3e2d1c0b9a8
Create Date: 2026-03-12 16:00:00.795643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f76ee12c80'
down_revision: Union[str, None] = 'f3e2d1c0b9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_categories',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_id'], ['tool_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_locations',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_cases',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('erp_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('available', 'assigned', 'in_repair', 'in_calibration', 'lost', 'retired', name='toolstatus'), nullable=False),
    sa.Column('condition', sa.Enum('new', 'good', 'fair', 'needs_repair', 'damaged', name='toolcondition'), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['tool_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'erp_code', name='uq_tool_cases_org_erp')
    )
    op.create_table('tools',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('erp_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('available', 'assigned', 'in_repair', 'in_calibration', 'lost', 'retired', name='toolstatus'), nullable=False),
    sa.Column('condition', sa.Enum('new', 'good', 'fair', 'needs_repair', 'damaged', name='toolcondition'), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('calibration_required', sa.Boolean(), nullable=False),
    sa.Column('calibration_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_calibration_date', sa.Date(), nullable=True),
    sa.Column('next_calibration_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['tool_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['tool_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['tool_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'erp_code', name='uq_tools_org_erp')
    )
    op.create_table('tool_assignments',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tool_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assignment_type', sa.Enum('employee', 'vehicle', 'department', 'section', 'location', name='toolassignmenttype'), nullable=False),
    sa.Column('assigned_to_employee_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assigned_to_vehicle_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('section', sa.String(length=200), nullable=True),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('condition_at_checkout', sa.Enum('new', 'good', 'fair', 'needs_repair', 'damaged', name='toolcondition'), nullable=True),
    sa.Column('condition_at_return', sa.Enum('new', 'good', 'fair', 'needs_repair', 'damaged', name='toolcondition'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_to_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['tool_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['tool_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tool_calibrations',
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tool_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('calibration_date', sa.Date(), nullable=False),
    sa.Column('next_calibration_date', sa.Date(), nullable=True),
    sa.Column('certificate_number', sa.String(length=200), nullable=True),
    sa.Column('calibrated_by', sa.String(length=200), nullable=True),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_calibrations')
    op.drop_table('tool_assignments')
    op.drop_table('tools')
    op.drop_table('tool_cases')
    op.drop_table('tool_locations')
    op.drop_table('tool_categories')
    # ### end Alembic commands ###
